services:
  dev_db:
    image: postgres:16.4
    container_name: dev_pg_db
    restart: always
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DB_EXTERNAL_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 8s
      timeout: 4s
      retries: 4
    env_file:
      - .env
volumes:
  dev_pg_data: